---
- name: Reload systemd
  systemd:
    daemon_reload: yes
  tags:
    - java-app
    - systemd

- name: Restart dummy-service
  systemd:
    name: "{{ dummy_service_name }}"
    state: restarted
  tags:
    - java-app
    - service
